name: todo_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  # Shared libraries
  common:
    path: shared_libraries/common
  component:
    path: shared_libraries/component
  core:
    path: shared_libraries/core
  dependencies:
    path: shared_libraries/dependencies
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Resources
  resources:
    path: resources

dev_dependencies:
  auto_route_generator:
  bloc_test: ^9.1.0
  build_runner:        
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
