name: register
description: Register Page
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  common:
    path: ../../shared_libraries/common
  component:
    path: ../../shared_libraries/component
  core:
    path: ../../shared_libraries/core
  dependencies:
    path: ../../shared_libraries/dependencies
  flutter:
    sdk: flutter
  resources:
    path: ../../resources
  router:
    path: ../../shared_libraries/router

dev_dependencies:
  build_runner:
  dart_code_metrics: ^4.17.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  hive_generator:
  json_serializable: '>4.4.0'
  retrofit_generator: '>=4.0.0 <5.0.0'
  very_good_analysis: ^3.0.1

flutter: